### ISSUE TITLE
Cryptography version

### ISSUE THREAD

**Issue by cafuentes1** [jaredhendrickson13/simple_acme_dns#13]
Hi @jaredhendrickson13,

Is there a reason not to use the latest version of cryptography? We want to use `simple_acme_dns` in our project but it conflicts with other packages that use cryptography 35.

PS: Awesome work! It's everything we needed and it works great. The docstrings explain the code masterfully.

**Comment by jaredhendrickson13** [comment]
This should be fixed by 87a49bbd8a05f1c2fd7f80ce0f5079158dcf3ea8. `cryptography` is already installed by `acme` so its inclusion was rather redundant.

Thanks!
